USB_VID = 0x2E8A
USB_PID = 0x000B	# XXX
USB_PRODUCT = "Obi Wan Komputer"
USB_MANUFACTURER = "NyanSat"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"

CIRCUITPY__EVE = 1
