USB_VID = 0x2E8A
USB_PID = 0x000C	# XXX
USB_PRODUCT = "Obi Wan Komputer (MRAM)"
USB_MANUFACTURER = "NyanSat"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"

BOOT2_SOURCE = boot_stage2/boot2_asxxxx204.S
BOOT2_S_CFLAGS = -DPICO_FLASH_SPI_CLKDIV=2 -DPICO_FLASH_SPI_RXDELAY=2 -DPICO_MRAM_XIP_READ_LATENCY=8

# ASxxxx204 16Mbit MRAM (2MiB total). Keep the first 1MiB protected for firmware/XIP.
USE_MRAM_STORAGE = 1
CFLAGS += -DCIRCUITPY_MRAM_TOTAL_BYTES='(2 * 1024 * 1024)'
# Keep a small 4KiB NVM region between firmware and filesystem.
CFLAGS += -DCIRCUITPY_INTERNAL_NVM_SIZE='(4 * 1024)'

CIRCUITPY__EVE = 1
